name: PR Comment Trigger

on:
  issue_comment:
    types: [created]

jobs:
  run-on-pr-comment:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/run') }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CI
        run: |
          COMMENT="${{ github.event.comment.body }}"
          echo "Raw PR Comment:"
          echo "$COMMENT"
          echo

          echo "Parsed repo and commit hash pairs:"
          echo "$COMMENT" | grep -oE '^[A-Za-z0-9_-]+:\s+[0-9a-f]{40}' || echo "No matches found"
      # 1. 检出 PR 对应的代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Python 环境（指定版本）
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install python-jenkins

      # 4. 运行你仓库中的 Python 脚本
      - name: Run Python script
        run: |
          ls -lR
          python jenkins_api_test/utils/jenkins_api.py --job "Model-Slicing-CI" --model_path "/wrk/xsjhdscratch_staff3/yuxiz/procyon2_quantized_onnx/detr_a8w8_p.onnx"
